<?php
/**
 * This file is part of the StenikBannersBundle.
 *
 * (c) Georgi Gyurov <georgi@stenik.bg>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Stenik\BannersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Custom methods for working with BannerZone entity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package StenikBannersBundle
 * @author Georgi Gyurov <georgi@stenik.bg>
 */
class BannerZoneRepository extends EntityRepository
{
}
